# TODO: Add meilisearch config
# Configure Meilisearch

# Meilisearch accepts a number of instance options during launch. You can configure these in two ways: environment variables and CLI arguments. Note that some options are only available as CLI arguments—consult our configuration reference for more details.
# https://www.meilisearch.com/docs/learn/self_hosted/configure_meilisearch_at_launch
services:
  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: meili-dictionary
    ports:
      - "7700:7700"
    env_file:
      - .env
    volumes:
      - ./meili-dictionary:/meili_data
    command: meilisearch --snapshot-dir /meili-dictionary/snapshots
    restart: unless-stopped

volumes:
  meili-dictionary:
    driver: local
