# TODO: Add meilisearch config
# Configure Meilisearch

# Meilisearch accepts a number of instance options during launch. You can configure these in two ways: environment variables and CLI arguments. Note that some options are only available as CLI arguments—consult our configuration reference for more details.
# https://www.meilisearch.com/docs/learn/self_hosted/configure_meilisearch_at_launch

services:
  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: meilisearch
    ports:
      - "7700:7700"
    expose:
      - 7700
    env_file:
      - ./testdata/test.env
    volumes:
      - ./meili_data_test:/meili_data
    command: meilisearch --snapshot-dir /meili_data/snapshots
    restart: unless-stopped

  test-app:
    image: app
    build:
      context: .
      args:
        progress: plain
      dockerfile: Dockerfile
    env_file:
      - testdata/test.env

    command: >
      sh -c "go test -v ./... -cover"

volumes:
  meili_data_test:
    driver: local
