# TODO: Add meilisearch config
# Configure Meilisearch

# Meilisearch accepts a number of instance options during launch. You can configure these in two ways: environment variables and CLI arguments. Note that some options are only available as CLI arguments—consult our configuration reference for more details.
# https://www.meilisearch.com/docs/learn/self_hosted/configure_meilisearch_at_launch
services:
  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: meilidb
    ports:
      - "7700:7700"
    expose:
      - "7700"
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data
    command: meilisearch
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  meili_data:
    driver: local
